// pastedev-frontend/src/App.tsx
const App = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen p-8">
      <h1 className="text-4xl font-bold text-gray-900 mb-4">Rsbuild with React</h1>
      <p className="text-lg text-gray-600">Start building amazing things with Rsbuild.</p>
    </div>
  );
};

export default App;

// pastedev-frontend/src/App.svelte
<main class="min-h-screen bg-gray-100 flex items-center justify-center">
    <div class="text-center">
        <h1 class="text-4xl font-bold text-gray-800 mb-4">Hello World</h1>
        <p class="text-lg text-gray-600">
            Welcome to your minimal Svelte + Tailwind CSS app
        </p>
    </div>
</main>
